#!/bin/sh
#
# @name My Drone
#
# @type Quadrotor H
#
# @maintainer Petr Stibinger <petr.stibinger@fel.cvut.cz>

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}

param set-default SIM_GZ_EN 1

param set-default MAV_TYPE 2

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default BAT1_N_CELLS 4
param set-default BAT1_CAPACITY 6800
param set-default BAT1_V_EMPTY 3.6
param set-default BAT1_V_CHARGED 4.2

param set-default CA_ROTOR0_PX 0.1725
param set-default CA_ROTOR0_PY 0.13
param set-default CA_ROTOR0_PZ -0.026
param set-default CA_ROTOR0_CT 1.0
param set-default CA_ROTOR0_KM -0.06

param set-default CA_ROTOR1_PX -0.1725
param set-default CA_ROTOR1_PY -0.13
param set-default CA_ROTOR1_PZ -0.026
param set-default CA_ROTOR1_CT 1.0
param set-default CA_ROTOR1_KM -0.06

param set-default CA_ROTOR2_PX 0.1725
param set-default CA_ROTOR2_PY -0.13
param set-default CA_ROTOR2_PZ -0.026
param set-default CA_ROTOR2_CT 1.0
param set-default CA_ROTOR2_KM 0.06

param set-default CA_ROTOR3_PX -0.1725
param set-default CA_ROTOR3_PY 0.13
param set-default CA_ROTOR3_PZ -0.026
param set-default CA_ROTOR3_CT 1.0
param set-default CA_ROTOR3_KM 0.06

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

# use the full available throttle range 0 - 1000
# the simulated ESC signal is cropped to integers :(
# this throttle mapping gives the highest signal resolution
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MIN3 0
param set-default SIM_GZ_EC_MIN4 0

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.57
